[project]
name = "ask-your-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.13.2",
    "fastapi>=0.136.1",
    "isort>=8.0.1",
    "langchain>=1.2.17",
    "langchain-community>=0.4.1",
    "langchain-huggingface>=1.2.2",
    "langdetect>=1.0.9",
    "loguru>=0.7.3",
    "mypy>=2.1.0",
    "psycopg-pool>=3.3.1",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
    "pymupdf>=1.27.2.3",
    "pytest>=9.0.3",
    "python-dotenv>=1.2.2",
    "streamlit>=1.56.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.19",
    "pytest>=9.0.3",
    "mypy>=2.1.0",
    "isort>=8.0.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["test"]
addopts = "--import-mode=importlib"

[tool.mypy]
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = ["langdetect.*"]
ignore_missing_imports = true

[tool.ruff]